version: 2
jobs:
  build: initial
    machine:
      image: windows-default # Windows machine image
    resource_class: windows.medium
    environment:
  CHROME_BIN: /usr/bin/google-chrome
    steps:
      # Commands are run in a Windows virtual machine environment
        - checkout
        - run: Write-Host 'Hello, Windows'
