version: 2

jobs:
  build: initial
  environment:
    CHROME_BIN : '/usr/bin/google-chrome'
    machine:
      image: windows-default # Windows machine image
    resource_class: windows.medium
    steps:
      # Commands are run in a Windows virtual machine environment
        - checkout
        - run: Write-Host 'Hello, Windows'
