version: 2
jobs:
  build:
    working_directory: ~/angular-testing
    docker:
      - image: circleci/node:10-browsers
    environment:
      CHROME_BIN: /usr/bin/google-chrome
    steps:
      - checkout
      - restore_cache:
          key:/angular-testing-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key:/angular-testing-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - run: npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js

